<?php

namespace Buseta\TallerBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Buseta\TallerBundle\Form\Model\DiagnosticoFilterModel;

/**
 * DiagnosticoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiagnosticoRepository extends EntityRepository
{
    public function filter(DiagnosticoFilterModel $filter = null)
    {
        $qb = $this->createQueryBuilder('d');
        $query = $qb->where($qb->expr()->eq(true,true));

        if($filter) {
            if ($filter->getNumero() !== null && $filter->getNumero() !== '') {
                $query->andWhere($query->expr()->like('d.numero',':numero'))
                    ->setParameter('numero',  sprintf('%%%s%%', $filter->getNumero()));
            }
            if ($filter->getReporte() !== null && $filter->getReporte() !== '') {
                $query->andWhere($query->expr()->eq('d.reporte', ':reporte'))
                    ->setParameter('reporte', $filter->getReporte());
            }
            if ($filter->getAutobus() !== null && $filter->getAutobus() !== '') {
                $query->andWhere($query->expr()->eq('d.autobus', ':autobus'))
                    ->setParameter('autobus', $filter->getAutobus());
            }
            if ($filter->getEstado() !== null && $filter->getEstado() !== '') {
                $query->andWhere($query->expr()->eq('d.estado', ':estado'))
                    ->setParameter('estado', $filter->getEstado());
            }
        }

        $query->orderBy('d.id', 'DESC');

        return $query->getQuery();
    }


    /**
     * Devuelve un array con el total de elementos y el total de elementos atrasados
     * de un estado pasado por parametro
     *
     * @param $estado El estado del diagnostico
     *
     * @return Array (['total']  ['atrasados'])
     */
    public function findTotalAtrasadas($estado = null)
    {
        $em = $this->getEntityManager();

        $qry= '
            SELECT   d.created AS fechahoracreado, d.estado, tp.minutos
            FROM     BusetaTallerBundle:Diagnostico d LEFT JOIN d.prioridad p LEFT JOIN p.tiempoPrioridad tp';
        $qry.=$estado == null? '': ' WHERE d.estado = :estado';

        $consulta = $em->createQuery($qry);

        if ($estado != null) {
            $consulta->setParameter('estado', $estado);
        }

        $filas =  $consulta->getArrayResult();
        $num_atrasadas = 0;

        foreach ($filas as $fila) {
            $minutos     = $fila['minutos'];
            $fechacreado = $fila['fechahoracreado'];
            $fechavence  = $fechacreado->modify('+'.$minutos.' minutes');
            $fechaahora  = new \DateTime('now');

            if (($fechavence < $fechaahora ) && ($fila['estado']!='PR'))  {
                $num_atrasadas++;
            }
        }

        //para devolver el total de filas
        $valor['total']= count($consulta->getResult());
        //para devolver el total de atrasadas
        $valor['atrasados']=   $estado != 'CO' ? $num_atrasadas:0;

        return $valor ;
    }

    /**
     * Devuelve un array con el total de elementos y el total de elementos atrasados
     * de un array de entidades pasado por parametro desde la consulta de filtro del formulario
     *
     * @param $estado El estado del Diagnostico
     *
     * @return Array (['total']  ['atrasados'])
     */
    public function findTotalAtrasadasFilter($entities = null)
    {

        $num_atrasadas = 0;

        foreach ($entities as $entity) {
            //si ocurre error no se cuenta como atrasada
            try {
                if ($entity->getPrioridad()) {
                    $minutos = $entity->getPrioridad()->getTiempoPrioridad()->getMinutos();
                    $fechacreado = $entity->getCreated();
                    if (($minutos != null) && ($minutos != null)) {
                        $fechavence = $fechacreado->modify('+' . $minutos . ' minutes');
                        $fechaahora = new \DateTime('now');
                        if (($fechavence < $fechaahora) && ($entity->getEstado() != 'PR')) {
                            $num_atrasadas++;
                        }
                    }
                }
            } catch (Exception $e) {
                continue;
            }
        }

        //para devolver el total de filas
        $valor['total']= count($entities);
        //para devolver el total de atrasadas
        $valor['atrasados']= $num_atrasadas ;

        return $valor ;
    }

}
