<?php

namespace Buseta\TallerBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Buseta\TallerBundle\Form\Model\DiagnosticoFilterModel;

/**
 * DiagnosticoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiagnosticoRepository extends EntityRepository
{
    public function filter(DiagnosticoFilterModel $filter = null)
    {
        $qb = $this->createQueryBuilder('d');
        $query = $qb->where($qb->expr()->eq(true,true));

        if($filter) {
            if ($filter->getReporte() !== null && $filter->getReporte() !== '') {
                $query->andWhere($query->expr()->eq('d.reporte', ':reporte'))
                    ->setParameter('reporte', $filter->getReporte());
            }
            if ($filter->getAutobus() !== null && $filter->getAutobus() !== '') {
                $query->andWhere($query->expr()->eq('d.autobus', ':autobus'))
                    ->setParameter('autobus', $filter->getAutobus());
            }
            if ($filter->getEstado() !== null && $filter->getEstado() !== '') {
                $query->andWhere($query->expr()->eq('d.estado', ':estado'))
                    ->setParameter('estado', $filter->getEstado());
            }
        }

        $query->orderBy('d.id', 'ASC');

        return $query->getQuery();
    }
}
