<?php

namespace Buseta\TallerBundle\Entity\Repository;

use Buseta\TallerBundle\Form\Model\ImpuestoFilterModel;
use Doctrine\ORM\EntityRepository;

/**
 * ImpuestoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImpuestoRepository extends EntityRepository
{
    public function filter(ImpuestoFilterModel $filter = null)
    {
        $qb = $this->createQueryBuilder('i');
        $query = $qb->where($qb->expr()->eq(true,true));

        if($filter) {
            if ($filter->getNumero() !== null && $filter->getNumero() !== '') {
                $query->andWhere($qb->expr()->like('i.numero',':numero'))
                    ->setParameter('numero', '%' . $filter->getNumero() . '%');
            }
            if ($filter->getNombre() !== null && $filter->getNombre() !== '') {
                $query->andWhere($qb->expr()->like('i.nombre',':nombre'))
                    ->setParameter('nombre', '%' . $filter->getNombre() . '%');
            }
            if ($filter->getTipo() !== null && $filter->getTipo() !== '') {
                $query->andWhere($query->expr()->eq('i.tipo', ':tipo'))
                    ->setParameter('tipo', $filter->getTipo());
            }
        }

        $query->orderBy('i.id', 'ASC');

        try {
            return $query->getQuery();
        } catch (NoResultException $e) {
            return array();
        }
    }
}
