<?php

namespace Buseta\TallerBundle\Entity\Repository;

/**
 * OrdenNecesidadProductoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrdenNecesidadProductoRepository extends \Doctrine\ORM\EntityRepository
{
}
