<?php

namespace Buseta\TallerBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * OrdenTrabajoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrdenTrabajoRepository extends EntityRepository
{
}
