<?php

namespace Buseta\TallerBundle\Entity\Repository;

use Buseta\TallerBundle\Form\Model\ReporteFilterModel;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;

/**
 * ReporteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReporteRepository extends EntityRepository
{
    public function filter($status = null, ReporteFilterModel $filter = null)
    {
        $qb = $this->createQueryBuilder('r');
        $query = $qb->where($qb->expr()->eq(true,true));

        if ($status !== null && $status !== '') {
            $query->andWhere($query->expr()->eq('r.estado', ':estado'))
                ->setParameter('estado', $status);
        }

        if($filter) {
            if ($filter->getNumero() !== null && $filter->getNumero() !== '') {
                $query->andWhere($qb->expr()->like('r.numero',':numero'))
                    ->setParameter('numero', '%' . $filter->getNumero() . '%');
            }
            if ($filter->getAutobus() !== null && $filter->getAutobus() !== '') {
                $query->andWhere($query->expr()->eq('r.autobus', ':autobus'))
                    ->setParameter('autobus', $filter->getAutobus());
            }
            if ($filter->getFechaInicio() !== null && $filter->getFechaInicio() !== '') {
                $fechaInicio = date_create_from_format('Y-m-d H:i:s', sprintf('%s 00:00:00', $filter->getFechaInicio()->format('Y-m-d')));
                $query->andWhere($query->expr()->gte('r.created', ':fechaInicio'))
                    ->setParameter('fechaInicio', $fechaInicio);
            }
            if ($filter->getFechaFin() !== null && $filter->getFechaFin() !== '') {
                $fechaFin = date_create_from_format('Y-m-d H:i:s', sprintf('%s 23:59:59', $filter->getFechaFin()->format('Y-m-d')));
                $query->andWhere($query->expr()->lte('r.created', ':fechaFin'))
                    ->setParameter('fechaFin', $fechaFin);
            }
        }

        $query->orderBy('r.id', 'ASC');

        try {
            return $query->getQuery();
        } catch (NoResultException $e) {
            return array();
        }
    }
}
