<?php

namespace Buseta\TallerBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;

/**
 * TareaMantenimientoRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TareaMantenimientoRepository extends EntityRepository
{
    public function onlyOneTarea($criteria = array())
    {
        $qb = $this->createQueryBuilder('t');
        $query = $qb->where($qb->expr()->eq(true,true));

        if ($criteria['valor'] !== null && $criteria['valor'] !== '') {
            $query->andWhere($query->expr()->eq('t.valor', ':valor'))
                ->setParameter('valor', $criteria['valor']);
        }
        if ($criteria['grupo'] !== null && $criteria['grupo'] !== '') {
            $query->andWhere($query->expr()->eq('t.grupo', ':grupo'))
                ->setParameter('grupo', $criteria['grupo']);
        }
        if ($criteria['subgrupo'] !== null && $criteria['subgrupo'] !== '') {
            $query->andWhere($query->expr()->eq('t.subgrupo', ':subgrupo'))
                ->setParameter('subgrupo', $criteria['subgrupo']);
        }

        try {
            return $query->getQuery()->getResult();
        } catch (NoResultException $e) {
            return array();
        }
    }
}
