<?php

namespace Buseta\BodegaBundle\Entity\Repository;

use Buseta\BodegaBundle\Form\Model\AlbaranFilterModel;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;

/**
 * AlbaranRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlbaranRepository extends EntityRepository
{
    public function filter(AlbaranFilterModel $filter = null)
    {
        $qb = $this->createQueryBuilder('a');
        $query = $qb->where($qb->expr()->eq(true,true));

        if($filter) {
            if ($filter->getNumeroReferencia() !== null && $filter->getNumeroReferencia() !== '') {
                $query->andWhere($qb->expr()->like('a.numeroReferencia',':numeroReferencia'))
                    ->setParameter('numeroReferencia', '%' . $filter->getNumeroReferencia() . '%');
            }
            if ($filter->getConsecutivoCompra() !== null && $filter->getConsecutivoCompra() !== '') {
                $query->andWhere($qb->expr()->like('a.consecutivoCompra',':consecutivoCompra'))
                    ->setParameter('consecutivoCompra', '%' . $filter->getConsecutivoCompra() . '%');
            }
            if ($filter->getAlmacen() !== null && $filter->getAlmacen() !== '') {
                $query->andWhere($query->expr()->eq('a.almacen', ':almacen'))
                    ->setParameter('almacen', $filter->getAlmacen());
            }
            if ($filter->getTercero() !== null && $filter->getTercero() !== '') {
                $query->andWhere($query->expr()->eq('a.tercero', ':tercero'))
                    ->setParameter('tercero', $filter->getTercero());
            }
        }

        $query->orderBy('a.id', 'ASC');

        try {
            return $query->getQuery();
        } catch (NoResultException $e) {
            return array();
        }
    }
}
