<?php

namespace Buseta\BodegaBundle\Entity\Repository;

use Buseta\BodegaBundle\Form\Model\BitacoraSerialFilterModel;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;

/**
 * BitacoraAlmacenRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BitacoraSerialRepository extends EntityRepository
{
    /**
     * @param BitacoraSerialFilterModel|null $filter
     *
     * @return array|\Doctrine\ORM\Query
     */
    public function filter(BitacoraSerialFilterModel $filter = null)
    {
        $qb = $this->createQueryBuilder('p');
        $query = $qb->where($qb->expr()->eq(true,true));

        if($filter) {
            if ($filter->getProducto() !== null && $filter->getProducto() !== '') {
                $query->andWhere($query->expr()->eq('p.producto', ':producto'))
                    ->setParameter('producto', $filter->getProducto());
            }
            if ($filter->getCategoriaProd() !== null && $filter->getCategoriaProd() !== '') {
                $query->andWhere($query->expr()->eq('p.categoriaProducto', ':categoriaprod'))
                    ->setParameter('categoriaprod', $filter->getCategoriaProd());
            }
            if ($filter->getAlmacen() !== null && $filter->getAlmacen() !== '') {
                $query->andWhere($qb->expr()->eq('p.almacen',':alma'))
                    ->setParameter('alma',  $filter->getAlmacen() );
            }
            if ($filter->getFechaInicio() !== null && $filter->getFechaInicio() !== '') {
                $query->andWhere($qb->expr()->gte('p.fechaMovimiento',':fechaInicio'))
                    ->setParameter('fechaInicio', $filter->getFechaInicio());
            }
            if ($filter->getFechaFin() !== null && $filter->getFechaFin() !== '') {
                $query->andWhere($qb->expr()->lte('p.fechaMovimiento',':fechaFin'))
                    ->setParameter('fechaFin', $filter->getFechaFin());
            }
            if ($filter->getTipoMovimiento() !== null && $filter->getTipoMovimiento() !== '') {
                $query->andWhere($qb->expr()->eq('p.tipoMovimiento',':tipoMovimiento'))
                    ->setParameter('tipoMovimiento', $filter->getTipoMovimiento());
            }
            if ($filter->getSerial() !== null && $filter->getSerial() !== '') {
                $query->andWhere($qb->expr()->eq('p.serial',':serial'))
                    ->setParameter('serial', $filter->getSerial());
            }
        }

        $query->orderBy('p.id', 'DESC');

        try {
            return $query->getQuery();
        } catch (NoResultException $e) {
            return array();
        }
    }
}
