<?php

namespace Buseta\BodegaBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;

/**
 * BitacoraAlmacenRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BitacoraAlmacenRepository extends EntityRepository
{

    public function filter(BitacoraAlmacenModel $filter = null)
    {
        $qb = $this->createQueryBuilder('b');
        $query = $qb->where($qb->expr()->eq(true,true));

        if($filter) {
            if ($filter->getCodigo() !== null && $filter->getCodigo() !== '') {
                $query->andWhere($qb->expr()->like('b.codigo',':codigo'))
                    ->setParameter('codigo', '%' . $filter->getCodigo() . '%');
            }
            if ($filter->getNombre() !== null && $filter->getNombre() !== '') {
                $query->andWhere($qb->expr()->like('b.nombre',':nombre'))
                    ->setParameter('nombre', '%' . $filter->getNombre() . '%');
            }
            if ($filter->getDireccion() !== null && $filter->getDireccion() !== '') {
                $query->andWhere($qb->expr()->like('b.direccion',':direccion'))
                    ->setParameter('direccion', '%' . $filter->getDireccion() . '%');
            }
        }

        $query->orderBy('b.id', 'ASC');

        try {
            return $query->getQuery();
        } catch (NoResultException $e) {
            return array();
        }
    }



}
