<?php

namespace Buseta\BodegaBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;

/**
 * InventarioFisicoLineaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InventarioFisicoLineaRepository extends EntityRepository
{
    public function findAllByInventarioFisicoId($id)
    {
        $qb = $this->createQueryBuilder('d');
        $query = $qb
            ->join('d.inventarioFisico', 't')
            ->where($qb->expr()->eq(':id', 't.id'))
            ->setParameter('id', $id);

        $query->orderBy('d.id', 'DESC');
        $query->getQuery();

        try {
            return $query->getQuery();
        } catch (NoResultException $e) {
            return array();
        }
    }
}
