<?php

namespace Buseta\BodegaBundle\Entity\Repository;

use Buseta\BodegaBundle\Form\Model\MovimientosProductosFilterModel;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;


/**
 * MovimientosProductosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovimientosProductosRepository extends EntityRepository
{
    public function consecutivoLast()
    {
        $qb = $this->_em->createQueryBuilder();

        $q = $qb->select('p.consecutivo_compra')
            ->from('BusetaBodegaBundle:MovimientosProductos', 'p')
            ->orderBy('p.consecutivo_compra','DESC')
            ->getQuery()
            ->setMaxResults(1);

        try {
            return $q->getSingleResult();
        } catch (NoResultException $e) {
            return false;
        }
    }


}
