<?php

namespace Buseta\BodegaBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;

/**
 * ProductoSeriadoRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductoSeriadoRepository extends EntityRepository
{

    public function buscarProductoSerial( $producto, $serial )
    {
        $q = "SELECT ps FROM BusetaBodegaBundle:ProductoSeriado ps WHERE ps.producto = :producto
               AND ps.serial = :serial ";

        $query = $this->_em->createQuery($q);

        $query->setParameter('producto', $producto)
              ->setParameter('serial', $serial);

        try {
            return $query->getResult();
        } catch (NoResultException $e) {
            //retorna falso si no existe
            return false;
        }
    }

}
