<?php

namespace Buseta\BodegaBundle\Entity\Repository;

use Buseta\BodegaBundle\Form\Model\ProductoTopeFilterModel;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;

/**
 * ProductoTopeRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductoTopeRepository extends EntityRepository
{

    public function filter(ProductoTopeFilterModel $filter = null)
    {
        $qb = $this->createQueryBuilder('p');
        $query = $qb->where($qb->expr()->eq(true, true));

        if ($filter) {
            if ($filter->getProducto() !== null && $filter->getProducto() !== '') {
                $query->andWhere($qb->expr()->eq('p.producto', ':producto'))
                    ->setParameter('producto', $filter->getProducto());
            }
            if ($filter->getAlmacen() !== null && $filter->getAlmacen() !== '') {
                $query->andWhere($qb->expr()->eq('p.almacen', ':almacen'))
                    ->setParameter('almacen', $filter->getAlmacen());
            }
        }

        $query->orderBy('p.id', 'ASC');

        try {
            return $query->getQuery();
        } catch (NoResultException $e) {
            return array();
        }
    }

}
