<?php

namespace Buseta\BodegaBundle\Entity\Repository;

use Buseta\BodegaBundle\Form\Model\SalidaBodegaFilterModel;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;

/**
 * SalidaBodegaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SalidaBodegaRepository extends EntityRepository
{
    public function filter(SalidaBodegaFilterModel $filter = null)
    {
        $qb = $this->createQueryBuilder('sb');
        $query = $qb->where($qb->expr()->eq(true,true));

        if($filter) {
            if ($filter->getCentroCosto() !== null && $filter->getCentroCosto() !== '') {
                $query->andWhere($query->expr()->eq('sb.centroCosto', ':centroCosto'))
                    ->setParameter('centroCosto', $filter->getCentroCosto());
            }
            if ($filter->getOrdenTrabajo() !== null && $filter->getOrdenTrabajo() !== '') {
                $query->andWhere($query->expr()->eq('sb.ordenTrabajo', ':ordenTrabajo'))
                    ->setParameter('ordenTrabajo', $filter->getOrdenTrabajo());
            }
            if ($filter->getResponsable() !== null && $filter->getResponsable() !== '') {
                $query->andWhere($query->expr()->eq('sb.responsable', ':responsable'))
                    ->setParameter('responsable', $filter->getResponsable());
            }
            if ($filter->getAlmacenOrigen() !== null && $filter->getAlmacenOrigen() !== '') {
                $query->andWhere($query->expr()->eq('sb.almacenOrigen', ':almacenOrigen'))
                    ->setParameter('almacenOrigen', $filter->getAlmacenOrigen());
            }
            if ($filter->getAlmacenDestino() !== null && $filter->getAlmacenDestino() !== '') {
                $query->andWhere($query->expr()->eq('sb.almacenDestino', ':almacenDestino'))
                    ->setParameter('almacenDestino', $filter->getAlmacenDestino());
            }
            if ($filter->getFechaInicio() !== null && $filter->getFechaInicio() !== '') {
                $query->andWhere($qb->expr()->gte('sb.fecha',':fechaInicio'))
                    ->setParameter('fechaInicio', $filter->getFechaInicio());
            }
            if ($filter->getFechaFin() !== null && $filter->getFechaFin() !== '') {
                $query->andWhere($qb->expr()->lte('sb.fecha',':fechaFin'))
                    ->setParameter('fechaFin', $filter->getFechaFin());
            }
            if ($filter->getEstado() !== null && $filter->getEstado() !== '') {
                $query->andWhere($query->expr()->eq('sb.estado_documento', ':estado'))
                    ->setParameter('estado', $filter->getEstado());
            }
            if ($filter->getProducto() !== null && $filter->getProducto() !== '') {
                $query->innerJoin('sb.salidas_productos', 'salidas_productos')
                    ->where($qb->expr()->andX(
                        $qb->expr()->eq('salidas_productos.producto',':producto')
                    ))
                    ->setParameter('producto', $filter->getProducto());
            }

        }

        $query->orderBy('sb.id', 'ASC');

        try {
            return $query->getQuery();
        } catch (NoResultException $e) {
            return array();
        }
    }
}
