<?php

namespace Buseta\NotificacionesBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ConfigNotificacionesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfigNotificacionesRepository extends EntityRepository
{
}
