<?php

namespace Buseta\NotificacionesBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NotificacionInternaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificacionInternaRepository extends EntityRepository
{
}
