<?php

namespace Buseta\CombustibleBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ConfiguracionCombustibleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfiguracionCombustibleRepository extends EntityRepository
{
}
