<?php

namespace Buseta\CombustibleBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NonUniqueResultException;

/**
 * ConfiguracionMarchamoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfiguracionMarchamoRepository extends EntityRepository
{
    public function getActiveConfiguration()
    {
        $qb = $this->createQueryBuilder('conf');
        $query = $qb->where($qb->expr()->andX(
            $qb->expr()->isNotNull('conf.producto'),
            $qb->expr()->isNotNull('conf.bodega')
        ))->getQuery();

        try {
            return $query->getSingleResult();
        } catch (NonUniqueResultException $ex) {
        } catch (\Exception $e) {
        }

        return null;
    }
}
