<?php

namespace Buseta\CombustibleBundle\Entity\Repository;

use Buseta\CombustibleBundle\Form\Model\ServicioCombustibleFilterModel;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;

/**
 * ServicioCombustibleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServicioCombustibleRepository extends EntityRepository
{
    public function filter(ServicioCombustibleFilterModel $filter = null)
    {
        $qb = $this->createQueryBuilder('s');
        $query = $qb->where($qb->expr()->eq(true,true));

        if($filter) {

            if ($filter->getCombustible() !== null && $filter->getCombustible() !== '') {
                $query->andWhere($query->expr()->eq('s.combustible', ':combustible'))
                    ->setParameter('combustible', $filter->getCombustible());
            }
            if ($filter->getVehiculo() !== null && $filter->getVehiculo() !== '') {
                $query->andWhere($query->expr()->eq('s.vehiculo', ':vehiculo'))
                    ->setParameter('vehiculo', $filter->getVehiculo());
            }
            if ($filter->getChofer() !== null && $filter->getChofer() !== '') {
                $query->andWhere($query->expr()->eq('s.chofer', ':chofer'))
                    ->setParameter('chofer', $filter->getChofer());
            }
        }

        $query->orderBy('s.id', 'ASC');

        try {
            return $query->getQuery();
        } catch (NoResultException $e) {
            return array();
        }
    }
}
