<?php

namespace Buseta\BusesBundle\Entity\Repository;

use Buseta\BusesBundle\Form\Model\AutobusFilterModel;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;

/**
 * AutobusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AutobusRepository extends EntityRepository
{
    public function filter(AutobusFilterModel $filter = null)
    {
        $qb = $this->createQueryBuilder('a');
        $query = $qb->where($qb->expr()->eq(true,true));

        if($filter) {
            if ($filter->getMatricula() !== null && $filter->getMatricula() !== '') {
                $query->andWhere($qb->expr()->like('a.matricula',':matricula'))
                    ->setParameter('matricula', '%' . $filter->getMatricula() . '%');
            }
            if ($filter->getNumero() !== null && $filter->getNumero() !== '') {
                $query->andWhere($qb->expr()->like('a.numero',':numero'))
                    ->setParameter('numero', '%' . $filter->getNumero() . '%');
            }
        }

        $query->orderBy('a.id', 'ASC');

        try {
            return $query->getQuery();
        } catch (NoResultException $e) {
            return array();
        }
    }

    /*public function buscarTodos($em)
    {
        $entities = $em->createQueryBuilder()
            ->select('a')
            ->from('BusetaBusesBundle:Autobus','a');

        $entities = $entities
            ->getQuery();

        return $entities;
    }

    public function buscarAutobus($busqueda,$em)
    {
        $entities = $em->createQueryBuilder()
            ->select('a')
            ->from('BusetaBusesBundle:Autobus','a');

        $datos = $busqueda->getData();
        $entities
            ->where('a.matricula LIKE :matricula');
        $entities
            ->setParameter('matricula', '%'.$datos['matricula'].'%');

        if($datos['marca']){
            $entities->andWhere('a.marca = :marca');
            $entities->setParameter('marca', $datos['marca']);
        }

        if($datos['color']){
            $entities->andWhere('a.color = :color');
            $entities->setParameter('color', $datos['color']);
        }

        if($datos['estilo']){
            $entities->andWhere('a.estilo = :estilo');
            $entities->setParameter('estilo', $datos['estilo']);
        }

        if($datos['combustible']){
            $entities->andWhere('a.combustible = :combustible');
            $entities->setParameter('combustible', $datos['combustible']);
        }

        if($datos['marca_motor']){
            $entities->andWhere('a.marca_motor = :marca_motor');
            $entities->setParameter('marca_motor', $datos['marca_motor']);
        }

        $entities = $entities
            ->getQuery();

        return $entities;
    }*/
}
