<?php

namespace Buseta\BusesBundle\Entity\Repository;

use Buseta\BusesBundle\Form\Model\ChoferFilterModel;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;

/**
 * ChoferRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChoferRepository extends EntityRepository
{
    public function filter(ChoferFilterModel $filter = null)
    {
        $qb = $this->createQueryBuilder('ch');
        $query = $qb->where($qb->expr()->eq(true,true));

        if($filter) {
            if ($filter->getNombres() !== null && $filter->getNombres() !== '') {
                $query->andWhere($qb->expr()->like('ch.nombres',':nombres'))
                    ->setParameter('nombres', '%' . $filter->getNombres() . '%');
            }
            if ($filter->getApellidos() !== null && $filter->getApellidos() !== '') {
                $query->andWhere($qb->expr()->like('ch.apellidos',':apellidos'))
                    ->setParameter('apellidos', '%' . $filter->getApellidos() . '%');
            }
            if ($filter->getCedula() !== null && $filter->getCedula() !== '') {
                $query->andWhere($qb->expr()->like('ch.cedula',':cedula'))
                    ->setParameter('cedula', '%' . $filter->getCedula() . '%');
            }
            if ($filter->getEstadoCivil() !== null && $filter->getEstadoCivil() !== '') {
                $query->andWhere($query->expr()->eq('ch.estadoCivil', ':estadoCivil'))
                    ->setParameter('estadoCivil', $filter->getEstadoCivil());
            }
            if ($filter->getNacionalidad() !== null && $filter->getNacionalidad() !== '') {
                $query->andWhere($query->expr()->eq('ch.nacionalidad', ':nacionalidad'))
                    ->setParameter('nacionalidad', $filter->getNacionalidad());
            }
        }

        $query->orderBy('ch.id', 'ASC');

        try {
            return $query->getQuery();
        } catch (NoResultException $e) {
            return array();
        }
    }

}
