<?php

namespace Buseta\BusesBundle\Entity\Repository;

use Buseta\BusesBundle\Form\Model\DespachadoraCombustibleFilterModel;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;

/**
 * DespachadoraCombustibleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DespachadoraCombustibleRepository extends EntityRepository
{
    public function filter(DespachadoraCombustibleFilterModel $filter = null)
    {
        $qb = $this->createQueryBuilder('d');
        $query = $qb->where($qb->expr()->eq(true,true));

        if($filter) {

            if ($filter->getCombustible() !== null && $filter->getCombustible() !== '') {
                $query->andWhere($query->expr()->eq('d.combustible', ':combustible'))
                    ->setParameter('combustible', $filter->getCombustible());
            }
            if ($filter->getAutobus() !== null && $filter->getAutobus() !== '') {
                $query->andWhere($query->expr()->eq('d.autobus', ':autobus'))
                    ->setParameter('autobus', $filter->getAutobus());
            }
            if ($filter->getChofer() !== null && $filter->getChofer() !== '') {
                $query->andWhere($query->expr()->eq('d.chofer', ':chofer'))
                    ->setParameter('chofer', $filter->getChofer());
            }
        }

        $query->orderBy('d.id', 'ASC');

        try {
            return $query->getQuery();
        } catch (NoResultException $e) {
            return array();
        }
    }
}
