<?php

namespace Buseta\NomencladorBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;

/**
 * CondicionRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MonedaRepository extends EntityRepository
{
    public function searchByValor($valores)
    {
        $q = "SELECT r FROM BusetaNomencladorBundle:Moneda r WHERE r.id = :valores";

        $query = $this->_em->createQuery($q);
        $query->setParameter('valores', $valores);

        try {
            return $query->getResult();
        } catch (NoResultException $e) {
            return false;
        }
    }

    public function onlyOneActive($criteria = array())
    {
        if ($criteria['activo'] === false) {
            return array();
        }

        $qb = $this->createQueryBuilder('m');
        $query = $qb->where($qb->expr()->eq('m.activo', ':activo'))
            ->setParameter('activo', true);

        try {
            return $query->getQuery()->getResult();
        } catch (NoResultException $e) {
            return array();
        }
    }
}
