<?php

namespace Buseta\BodegaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AlbaranRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlbaranRepository extends EntityRepository
{
}
