<?php

namespace Buseta\BodegaBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;

/**
 * InformeStockRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InformeStockRepository extends EntityRepository
{
    public function comprobarInformeStock($almacen, $producto)
    {
        $qb = $this->_em->createQueryBuilder();

        $q = $qb->select('o')
            ->from('BusetaBodegaBundle:InformeStock', 'o')
            ->where('o.almacen = :almacen')
            ->andWhere('o.producto = :producto')
            ->setParameter('almacen', $almacen)
            ->setParameter('producto', $producto)
            ->getQuery();

        try {
            return $q->getSingleResult();
        } catch (NoResultException $e) {
            return false;
        }
    }

    public function busquedaInformeStock($filter = array())
    {
        $qb = $this->_em->createQueryBuilder();

        $q = $qb->select('o')
            ->from('BusetaBodegaBundle:BitacoraAlmacen', 'o')
            ->where($qb->expr()->eq(true, true));

        if ($filter['almacen'] !== null && $filter['almacen'] !== '') {
            $q->andWhere('o.almacen = :almacen')
                ->setParameter('almacen', $filter['almacen']);
        }

        if ($filter['producto'] !== null && $filter['producto'] !== '') {
            $q->andWhere('o.almacen = :almacen')
                ->setParameter('producto', $filter['producto']);
        }

        if ($filter['fecha'] !== null && $filter['fecha'] !== '') {
            $q->andWhere('o.fechaMovimiento = :fecha')
                ->setParameter('fecha', $filter['fecha']);
        }

        $q = $q->getQuery(); //Se devuelve para paginar

        try {
            return $q->getResult(); //No se debe devolver para paginar, es mas trabajoso
        } catch (NoResultException $e) {
            return array();
        }
    }

    public function buscarTodos()
    {
        $qb = $this->_em->createQueryBuilder();

        $q = $qb->select('o')
            ->from('BusetaBodegaBundle:BitacoraAlmacen', 'o')
            ->getQuery();

        try {
            return $q->getResult();
        } catch (NoResultException $e) {
            return false;
        }
    }

    public function buscarAlmacenBitacora($almacen, $fecha)
    {
        $qb = $this->_em->createQueryBuilder();

        $q = $qb->select('o')
            ->from('BusetaBodegaBundle:BitacoraAlmacen', 'o')
            ->where('o.almacen = :almacen')
            ->andWhere('o.fechaMovimiento < :fecha')
            ->setParameter('almacen', $almacen)
            ->setParameter('fecha', $fecha)
            ->getQuery();

        try {
            return $q->getResult();
        } catch (NoResultException $e) {
            return false;
        }
    }
}
