<?php

namespace Buseta\BodegaBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;

/**
 * InformeStockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InformeStockRepository extends EntityRepository
{
    public function comprobarInformeStock($almacen,$producto)
    {
        $qb = $this->_em->createQueryBuilder();

        $q = $qb->select('o')
            ->from('BusetaBodegaBundle:InformeStock', 'o')
            ->where('o.almacen = :almacen')
            ->andWhere('o.producto = :producto')
            ->setParameter('almacen', $almacen)
            ->setParameter('producto', $producto)
            ->getQuery();

        try {
            return $q->getSingleResult();
        } catch (NoResultException $e) {
            return false;
        }
    }

}
