<?php

namespace Buseta\BodegaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PrecioProductoRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrecioProductoRepository extends EntityRepository
{
}
