<?php

namespace Buseta\CoreBundle\Validator\Constraints;

use Symfony\Component\Validator\Constraint;

/**
 * Class CodigoBarrasValido
 * @package Buseta\CoreBundle\Validator\Constraints
 * @Annotation
 */
class CodigoYPinValido extends Constraint{

    public $messageBarras = 'Los datos de código de barras relacionados con el chofer no son válidos.';
    public $messagePin = 'El Pin proporcionado no es válido.';

    public function getTargets()
    {
        return self::CLASS_CONSTRAINT;
    }

    public function validatedBy()
    {
        return 'codigoYpin_validador'; // TODO: Change the autogenerated stub
    }


}